parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # Configure these for your database server

        # Mysql
        driver: 'pdo_mysql'
        server_version: '5.2'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # PostgreSQL
        # driver: 'pdo_pgsql'
        # server_version: '9.6'
        # charset: utf8

        #SQLLite
        # driver:   pdo_sqlite
        # charset: utf8

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping'
                prefix: 'App\Entity'
                alias: App
