api.config.configuration:
  path: /
  controller: App\Controller\ApiConfigController::getConfiguration

api.config.user:
  path: /user
  controller: App\Controller\ApiConfigController::getUserData

api.config.user.edit.password:
  path: /user/edit-password
  controller: App\Controller\ApiConfigController::updatePassword
  methods: 'POST'

api.config.user.edit.email:
  path: /user/edit-email
  controller: App\Controller\ApiConfigController::updateEmail
  methods: 'POST'

api.config.user.delete:
  path: /user/delete
  controller: App\Controller\ApiConfigController::deleteAccount
  methods: 'POST'

api.config.places:
  path: /places
  controller: App\Controller\ApiConfigController::getPlaces

api.config.notifications:
  path: /notifications
  controller: App\Controller\ApiConfigController::getNotifications
