api.data.point:
  path: /point/{feedDataId}/{frequence}/{debut}/{fin}
  controller: App\Controller\ApiDataController::getPointAction

api.data.repartition:
  path: /repartition/{feedDataId}/{frequence}/{colonne}/{debut}/{fin}
  controller: App\Controller\ApiDataController::getRepartitionAction

api.data.double_repartition:
  path: /double_repartition/{feedDataId}/{frequence}/{colonneX}/{colonneY}/{debut}/{fin}
  controller: App\Controller\ApiDataController::getDoubleRepartitionAction

api.data.croisement:
  path: /croisement/{feedDataId}/{frequence}/{colonneX}/{colonneY}/{debut}/{fin}
  controller: App\Controller\ApiDataController::getDoubleRepartitionAction

api.data.somme:
  path: /somme/{feedDataId}/{frequence}/{debut}/{fin}
  controller: App\Controller\ApiDataController::getSemaineAction

api.data.nombreInferieur:
  path: /inf/{feedDataId}/{valeur}/{frequence}/{debut}/{fin}
  controller: App\Controller\ApiDataController::getNombreInferieurAction
