configuration:
    resource: "./configuration.yaml"
    prefix: /config

data:
    resource: "./data.yaml"
    prefix: /data

place:
    resource: "./place.yaml"
    prefix: /place

feed:
    resource: "./feed.yaml"
    prefix: /feed