api.configuration:
  path: api/config
  controller: App\Controller\ApiConfigController::getConfigurationAction

api.user:
  path: api/config/user
  controller: App\Controller\ApiConfigController::getUserAction

api.user.edit.password:
  path: api/config/user/edit-password
  controller: App\Controller\ApiConfigController::updatePassword
  methods: 'POST'

api.configuration.places:
  path: api/config/places
  controller: App\Controller\ApiConfigController::getPlacesAction
