data.repartition:
  path: /data/{placeId}/repartition/{dataType}/{repartitionType}/{start}/{end}
  controller: App\Controller\DataController::getRepartionAction

data.evolution:
  path: /data/{placeId}/evolution/{dataType}/{frequency}/{start}/{end}
  controller: App\Controller\DataController::getEvolutionAction

data.sum-group-by:
  path: /data/{placeId}/sum-group/{dataType}/{frequency}/{groupBy}/{start}/{end}
  controller: App\Controller\DataController::getSumGroupByAction

data.sum:
  path: /data/{placeId}/sum/{dataType}/{start}/{end}
  controller: App\Controller\DataController::getSumAction

data.number:
  path: /data/{placeId}/inf/{dataType}/{value}/{frequency}/{start}/{end}
  controller: App\Controller\DataController::getNumberInfAction

data.xy:
  path: /data/{placeId}/xy/{dataTypeX}/{dataTypeY}/{frequency}/{start}/{end}
  controller: App\Controller\DataController::getXYAction
