# Users related routes

security.login:
  path: /login
  controller: App\Controller\SecurityController::login

security.logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
