<?php

namespace AppBundle\Repository;

use AppBundle\Entity\DataValue;
use AppBundle\Entity\FeedData;
use Doctrine\ORM\QueryBuilder;
use AppBundle\Controller\DataApiController;

/**
 * DataValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataValueRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Get an average value
   *
   * @param \DateTime $startDate
   * @param \DateTime $endDate
   * @param int $frequency
   */
  public function getAverageValue(\DateTime $startDate, \DateTime $endDate, FeedData $feedData, $frequency)
  {
      // Create the query builder
      $queryBuilder = $this->createQueryBuilder('d');

      $queryBuilder->select('AVG(d.value) AS value');
      $this->betweenDateWithFeedDataAndFrequency($startDate, $endDate, $feedData, $frequency, $queryBuilder);
      $queryBuilder->groupBy('d.id');
      return $queryBuilder
          ->getQuery()
          ->getScalarResult();
  }

  /**
   * Get sum of value
   *
   * @param \DateTime $startDate
   * @param \DateTime $endDate
   * @param string $frequency
   */
  public function getSumValue(\DateTime $startDate, \DateTime $endDate, FeedData $feedData, $frequency)
  {
      // Create the query builder
      $queryBuilder = $this->createQueryBuilder('d');

      $queryBuilder->select('SUM(d.value) AS value');
      $this->betweenDateWithFeedDataAndFrequency($startDate, $endDate, $feedData, $frequency, $queryBuilder);
      $queryBuilder->groupBy('d.id');

      return $queryBuilder
          ->getQuery()
          ->getScalarResult();
  }

  /**
   * Get value
   *
   * @param \DateTime $startDate
   * @param \DateTime $endDate
   * @param string $frequency
   */
  public function getValue(\DateTime $startDate, \DateTime $endDate, FeedData $feedData, $frequency)
  {
      // Create the query builder
      $queryBuilder = $this->createQueryBuilder('d');

      $this->betweenDateWithFeedDataAndFrequency($startDate, $endDate, $feedData, $frequency, $queryBuilder);

      return $queryBuilder
          ->getQuery()
          ->getResult();
  }

  /**
   * Get repartition
   *
   * @param \DateTime $startDate
   * @param \DateTime $endDate
   * @param string $frequency
   */
  public function getRepartitionValue(\DateTime $startDate, \DateTime $endDate, FeedData $feedData, $axeX, $axeY, $frequency, $repartitionType)
  {
      // Create the query builder
      $queryBuilder = $this->createQueryBuilder('d');

      $queryBuilder->select('AVG(d.value) value, d.' . $axeX . ' AS axeX, d.' . $axeY . ' AS axeY');
      $this->betweenDateWithFeedDataAndFrequency($startDate, $endDate, $feedData, $frequency, $queryBuilder);
      $queryBuilder->groupBy('d.' . $axeX);
      $queryBuilder->groupBy('d.' . $axeY);

      // If this is a year repartition, we also group by year.
      if (in_array($repartitionType, [DataApiController::YEAR_HORIZONTAL_REPARTITION, DataApiController::YEAR_VERTICAL_REPARTITION])) {
        $queryBuilder->addSelect('d.year year');
        $queryBuilder->groupBy('d.year');
      }

      return $queryBuilder
          ->getQuery()
          ->getResult() ;
  }

  public function betweenDateWithFeedDataAndFrequency(\DateTime $startDate, \DateTime $endDate, FeedData $feedData, $frequency, QueryBuilder &$queryBuilder)
  {
      $queryBuilder
          ->andWhere('d.date BETWEEN :start AND :end')
          ->setParameter('start', $startDate)
          ->setParameter('end',   $endDate)
          // Add condition on feedData
          ->andWhere('d.feedData = :feedData')
          ->setParameter('feedData', $feedData->getId())
          // Add condition on frequency
        ->andWhere('d.frequency = :frequency')
        ->setParameter('frequency', $frequency);
  }
}
