<?php

namespace AppBundle\Repository;

/**
 * FeedTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
