<?php

namespace AppBundle\Repository;

/**
 * FeedRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
