<?php

namespace AppBundle\Repository;

/**
 * FeedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedDataRepository extends \Doctrine\ORM\EntityRepository
{
}
