<?php

namespace AppBundle\Repository;

/**
 * FrequencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrequencyRepository extends \Doctrine\ORM\EntityRepository
{
}
