<?php

namespace App\Repository;

use App\Entity\Feed;

/**
 * FeedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedDataRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Get sum of value
   *
   * @param \DateTime $startDate
   * @param \DateTime $endDate
   * @param string $frequency
   */
  public function findOneByFeedAndDataType(Feed $feed, $dataType)
  {
    // Create the query builder
    $queryBuilder = $this
    ->createQueryBuilder('df')
    ->andWhere('df.feed = :feed')
    ->setParameter('feed', $feed->getId())
    ->andWhere('df.dataType = :data_type')
    ->setParameter('data_type', $dataType);

    return $queryBuilder
    ->getQuery()
    ->getScalarResult();
  }
}
