<?php

namespace App\Repository;

use App\Entity\Notification;
use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Notification::class);
    }

    /**
     * @return Notification[]
     */
    public function findNotificationForUser(User $user): iterable
    {
        return $this
            ->createQueryBuilder('n', 'n.id')
            ->select()
            ->where('user = :user')
            ->setParameter('user', $user)
            ->orderBy('date')
            ->getQuery()
            ->getResult()
        ;
    }
}
