<?php

namespace App\Repository;

use App\Entity\PendingAction;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PendingActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingActionRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, PendingAction::class);
    }

    /**
     * @return PendingAction[]
     */
    public function findExpiredActions(): iterable
    {
        return $this
            ->createQueryBuilder('a', 'a.id')
            ->select()
            ->where('a.expirationDate <= :date')
            ->setParameter('date', new \DateTimeImmutable())
            ->getQuery()
            ->getResult()
        ;
    }
}
