<?php

namespace App\Repository;

use App\Entity\Place;
use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Place Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Place::class);
    }

    /**
     * Remove ALL data (feed, feedData and dataValue) for a place and then place itself
     */
    public function purge(Place $place)
    {
        $feedRepository = $this
            ->getEntityManager()
            ->getRepository('App:Feed')
        ;

        foreach ($feedRepository->findByPlace($place) as $feed) {
            $feedRepository->purge($feed);

        }

        $this
            ->createQueryBuilder('p')
            ->delete()
            ->where('p.id = :id')
            ->setParameter('id', $place->getId())
            ->getQuery()
            ->execute()
        ;
    }

    public function getAllowedPlaces(User $user)
    {

        $queryBuilder = $this->createQueryBuilder('p');

        return $queryBuilder
            ->select()
            ->orWhere('p.user = :user')
            ->orWhere(':user MEMBER OF p.allowedUsers')
            ->orWhere('p.public = true')
            ->setParameter('user', $user)
            ->orderBy('p.name', 'asc')
            ->getQuery()
            ->getResult()
        ;
    }
}
