monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            action_level: info
            date_format: Y-m-d
            max_files: 10
            channels: ["!php"]
        php:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%-php.log"
            date_format: Y-m-d
            max_files: 30
            level: warning
            formatter: monolog.formatter.line # Overriden using goat to display PID
            channels: ["php"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
