# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    aeneria.version: '0.5.4'
    aeneria.repo_git: 'https://gitlab.com/aeneria/aeneria-app'
    aeneria.documentation: 'https://docs.aeneria.com/fr/'
    aeneria.user.max_places: "%env(AENERIA_USER_MAX_PLACES)%"
    aeneria.user.can_share_place: "%env(AENERIA_USER_CAN_SHARE_PLACE)%"
    aeneria.user.can_fetch: "%env(AENERIA_USER_CAN_FETCH)%"
    aeneria.user.can_export: "%env(AENERIA_USER_CAN_EXPORT)%"
    aeneria.place_can_be_public: "%env(AENERIA_PLACE_CAN_BE_PUBLIC)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: "%kernel.project_dir%"
            $userMaxPlaces: "%aeneria.user.max_places%"
            $userCanSharePlace: "%aeneria.user.can_share_place%"
            $userCanFetch: "%aeneria.user.can_fetch%"
            $userCanExport: "%aeneria.user.can_export%"
            $placeCanBePublic: "%aeneria.place_can_be_public%"

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Repository\:
        public: true # For unit tests
        resource: '../src/Repository'
        tags: ['doctrine.repository']

    App\Twig\:
        resource: '../src/Twig'
        tags: ['twig.extension', 'container.hot_path']