app.home:
  path: /app
  controller: App\Controller\AppController::appAction

app.home.trailing:
  path: /app/{slug}
  controller: App\Controller\AppController::appAction
  requirements:
    slug: .+

api:
  resource: "./api/index.yaml"
  prefix: /api

security.logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

security.login:
  path: /login
  controller: App\Controller\SecurityController::login

app.root:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app.home
    permanent: true

# En dernier recours, on redirige vers /app/{path} au cas où, si cette page
# n'existe pas non-plus dans l'app vue, c'est elle qui se chargera de faire une 404
app.redirect.ultime:
  path: /{slug}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  requirements:
    slug: .+
  defaults:
    route: app.home.trailing
    permanent: true
